// Mocks generated by Mockito 5.0.15 from annotations
// in restaurant_app/test/restaurant_provider_test/provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_app/config/api_config.dart' as _i3;
import 'package:restaurant_app/models/restaurant.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeRestaurantsResult_0 extends _i1.Fake
    implements _i2.RestaurantsResult {}

/// A class which mocks [RestaurantAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantAPI extends _i1.Mock implements _i3.RestaurantAPI {
  MockRestaurantAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RestaurantsResult> getListOfRestaurant() =>
      (super.noSuchMethod(Invocation.method(#getListOfRestaurant, []),
              returnValue: Future<_i2.RestaurantsResult>.value(
                  _FakeRestaurantsResult_0()))
          as _i4.Future<_i2.RestaurantsResult>);
  @override
  String toString() => super.toString();
}
